
    name: MockToDo
    
    on:
     push:
      branches: [ "main" ]

    jobs:
     build_project:
       runs-on: macos-latest
       steps:
       - name: Checkout repository
         uses: actions/checkout@v2
         
       - name: Build and Test
         run: |
          xcodebuild \
           -project MockToDo \
           -scheme MockToDo \
           -sdk iphonesimulator \
           -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
